http:
  listner:
     host: "localhost"
     port: "8081"
     path: "/travelontipcall/{ServiceType}"
     
db:
  oracle:
    host: "localhost"
    port: "1521"
    user: "system"
    password: "system"
    instance: ""
     